version: "3"
services:
  node-server:
    container_name: node-app
    build: .
    ports: 
      - "3001:3000"
  mongodb:
    container_name: mongo_database
    image: mongo
    ports:
      - "27017:27017"