version: "3"

services:
  node_server:
    container_name: node_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - bridge_network
    environment:
      - DB_HOST=mongodb://mongo_database/Blogapp
      - ADMIN_ACCOUNT=deneme@gmail.com
      - JWT_SECRET=secret_key
    
  mongodb:
    container_name: mongo_database
    image: mongo
    ports:
      - "60600:27017"
    networks:
      - bridge_network
    volumes:
      - blogAppDatabase:/data/db

networks:
  bridge_network:
    driver: bridge

volumes:
  blogAppDatabase:
    driver: local